### ISSUE TITLE
Specs fail on nsqd 0.3.6

### ISSUE THREAD

**Issue by bschwartz** [wistia/nsq-ruby#19]
```
$ nsqd -version
nsqd v0.3.6 (built w/go1.5.1)
```

```
Failures:

  1) Nsq::Consumer with a low message timeout should give us the same message over and over
     Failure/Error: assert_no_timeout do
       expected no Exception, got #<Timeout::Error: execution expired> with backtrace:
         # ./lib/nsq/consumer.rb:47:in `pop'
         # ./lib/nsq/consumer.rb:47:in `pop'
         # ./spec/lib/nsq/consumer_spec.rb:165:in `block (4 levels) in <top (required)>'
         # ./spec/spec_helper.rb:24:in `block (2 levels) in assert_no_timeout'
         # ./spec/spec_helper.rb:23:in `block in assert_no_timeout'
         # ./spec/spec_helper.rb:22:in `assert_no_timeout'
         # ./spec/lib/nsq/consumer_spec.rb:164:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:22:in `assert_no_timeout'
     # ./spec/lib/nsq/consumer_spec.rb:164:in `block (3 levels) in <top (required)>'

  2) Nsq::Producer connecting directly to a single nsqd #write will attempt to resend messages when it reconnects to nsqd
     Failure/Error: assert_no_timeout(5) do
       expected no Exception, got #<Timeout::Error: execution expired> with backtrace:
         # ./lib/nsq/consumer.rb:47:in `pop'
         # ./lib/nsq/consumer.rb:47:in `pop'
         # ./spec/lib/nsq/producer_spec.rb:99:in `block (6 levels) in <top (required)>'
         # ./spec/lib/nsq/producer_spec.rb:98:in `times'
         # ./spec/lib/nsq/producer_spec.rb:98:in `block (5 levels) in <top (required)>'
         # ./spec/spec_helper.rb:24:in `block (2 levels) in assert_no_timeout'
         # ./spec/spec_helper.rb:23:in `block in assert_no_timeout'
         # ./spec/spec_helper.rb:22:in `assert_no_timeout'
         # ./spec/lib/nsq/producer_spec.rb:94:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:22:in `assert_no_timeout'
     # ./spec/lib/nsq/producer_spec.rb:94:in `block (4 levels) in <top (required)>'
```
